### ISSUE TITLE
Error -4077 //  ECONNRESET 

### ISSUE THREAD

**Issue by Solotov** [Corteks-team/mysql_data_generator#14]
![image](https://user-images.githubusercontent.com/4804666/152658794-e79c7756-bcd7-4ee6-9f1d-84558ffceaef.png)

- [ ] PS E:\src\project\orbicall2\dist> mysqldatagen --db mysql://orbmaster:root@127.0.0.1:3306/orbicall2
- [ ] * [n] => Skip the current table. Only works during data generation phase.
- [ ] [2022-02-05T21:54:57.864] [WARN] default - For performance foreign_key_checks, autocommit and unique_checks are disabled during insert.
- [ ] [2022-02-05T21:54:57.866] [WARN] default - They are disabled per connections and should not alter your configuration.
- [ ] [2022-02-05T21:54:57.867] [INFO] default - To improve performances further you can update innodb_autoinc_lock_mode = 0 in your my.ini.
- [ ] [2022-02-05T21:54:57.939] [INFO] default - No scripts provided.
- [ ] [2022-02-05T21:54:58.033] [INFO] default - fill:  events
- [ ] [2022-02-05T21:54:58.037] [INFO] default - 50 / 1000
- [ ] [2022-02-05T21:55:09.181] [ERROR] default - ECONNRESET Error
- [ ] [2022-02-05T21:55:09.183] [ERROR] default - Error: read ECONNRESET
- [ ]     at TCP.onStreamRead (node:internal/stream_base_commons:211:20)
- [ ]     --------------------
- [ ]     at Protocol._enqueue (C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\mysql\lib\protocol\Protocol.js:144:48)
- [ ]     at Connection.query (C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\mysql\lib\Connection.js:198:25)
- [ ]     at C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\knex\lib\dialects\mysql\index.js:134:18
- [ ]     at new Promise (<anonymous>)
- [ ]     at Client_MySQL._query (C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\knex\lib\dialects\mysql\index.js:128:12)
- [ ]     at Client_MySQL.query (C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\knex\lib\client.js:167:17)
- [ ]     at Runner.query (C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\knex\lib\runner.js:134:36)
- [ ]     at C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\knex\lib\runner.js:40:23
- [ ]     at C:\Users\AXA\AppData\Roaming\npm\node_modules\@corteks\mysql-data-generator\node_modules\knex\lib\runner.js:260:24
- [ ]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
- [ ]   errno: -4077,
- [ ]   code: 'ECONNRESET',
- [ ]   syscall: 'read',
- [ ]   fatal: true
- [ ] }
- [ ] [2022-02-05T21:55:09.185] [INFO] default - Close database connection
- [ ]

**Comment by Raphael67** [comment]
Hi @Solotov , can you look at your mysql server logs please ?

**Comment by Solotov** [comment]
[mysql_err.log](https://github.com/Corteks-team/mysql_data_generator/files/8017594/mysql_err.log)

**Comment by Raphael67** [comment]
Your error file is nearly one year long. Are you using innoDB ? If yes, your innodb_buffer_pool_size is definitely too small.
Please give us more information otherwise we won't be able to help you.

**Comment by Solotov** [comment]
> Executed the script more than once but on the mysql server side it does not throw any exception, also generate some data with an application "dbForge Data Generator for MySQL", it does not give that problem. 

 
**Possible solution**
[The reason and solution for the error ECONNRESET of the httpClieint request of Node.js](https://programmerah.com/the-reason-and-solution-for-the-error-econnreset-of-the-httpclieint-request-of-node-js-29961/)

**Comment by Raphael67** [comment]
This has nothing to do with an HTTP connection. Can you try to bump up the max_allowed_packet ? You can also update your custom_schema.json to remove tables or reduce generated data size to narrow the issue.

**Comment by Raphael67** [comment]
Have you tried increasing max_allowed_packet ? Try to narrow the problem by reducing the number of tables to fill or the number of rows to generate per table. If you can provide me with a small example to reproduce this issue I would be really happy to investigate.

**Comment by Raphael67** [comment]
Without further information I will close this issue. If this appears again do not hesitate to reopen one with more information. Thank you.
